[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

startupCheckTimeout = 180

[deploy.env]
# These can be overridden in Railway dashboard
# LOG_LEVEL = "INFO"
# BUREAU_PORT = "8888"